name: Build and Deploy

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn package -DskipTests
      - name: Deploy p2 site
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          git config user.email "workflows@egithub.com"
          git config user.name "workflows@egithub.com"
          mkdir -p ./p2/
          cp -r ./gap.eclipse.plugins.site/target/repository ./p2/nightly
          git add -f ./p2/nightly/*
          git stash
          git fetch --all
          git checkout --track origin/gh-pages
          git rm -rf --ignore-unmatch ./p2/nightly/*
          git clean -df
          git stash pop
          git add -f ./p2/nightly/*
          git commit -m "Deploy artifacts to p2 update site"
          git push origin gh-pages
          git switch master
          echo "Deployed successfully"
          
